import React from 'react'
import CustomLabel from '../index'
import { Text } from '@fluentui/react'

const Story = {
  title: 'Components/Custom Label',
  component: CustomLabel,
}

const Template = (args) => <CustomLabel {...args} />

export const Default = Template.bind({})
Default.args = {
  labelWrapperStack: {
    horizontal: true,
    verticalAlign: 'center',
    tokens: {
      childrenGap: 4,
      maxWidth: 300,
    },
  },
  label: 'Timestamp',
  callout: {
    target: '#my-callout',
  },
  iconButton: {
    id: 'my-callout',
    styles: {
      root: {
        marginBottom: -3,
      },
    },
    title: 'Info',
    iconProps: {
      iconName: 'Info',
    },
  },
  showCallout: false,
  contentWrapperStack: {
    styles: {
      root: {
        padding: 10,
        maxWidth: 200,
      },
    },
  },
  calloutContent: (
    <Text variant="small">
      This timestamp is generated by the values in Date, Time and Timezone
      fields.
    </Text>
  ),
}

export default Story
