import React from 'react'
import CustomLabel from '../index'

export default {
  title: 'Components/Custom Label',
  component: CustomLabel
}

const Template = (args) => <CustomLabel {...args} />

export const Default = Template.bind({});
Default.args = {
  labelWrapperStack: {
    horizontal:  true,
    verticalAlign: 'center',
    tokens: {
      childrenGap: 4,
      maxWidth: 300,
    }
  },
  label: 'Timestamp',
  callout: {
    target: '#my-callout'
  },
  iconButton: {
    id: 'my-callout',
    styles: {
      root: {
        marginBottom: -3,
        paddingBottom: 2
        // outline: '1px blue solid'
      }
    },
    title: 'Info',
    iconProps: {
      iconName: 'Info'
    }
  },
  showCallout: true,
  contentWrapperStack: {},
  calloutContent: 'This timestamp is generated by the values in Date, Time and Timezone fields'
}
