# .github/workflows/chromatic.yml
# name of our action
name: 'Chromatic Deployment'
# the event that will trigger the action
on:
  push:
    tags:
    - '*'
# what the action will do
jobs:
  Yarn:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Yarn
        run: yarn
      - name: Deploy Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-my-storybook
