name: React Mark JS NPM Package
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Configure Git User
        run: |
          git remote rm origin
          git remote add origin "https://$USER_NAME:$GH_PAT@github.com/appsparkler/my-workspace.git"
          git fetch
          git config --global user.email subs@appsparkler.com
          git config --global user.name Aakash Shah
      - name: Yarn
        run: yarn
      - name: Lerna Publish
        run: npx lerna publish --conventional-commits --yes
        env:
          NODE_ENV: 'production'
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
