name: React Mark JS NPM Package
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn lerna publish
        env:
          NODE_ENV: 'production'
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
